In [144]:
!pip install numpy --upgrade 

Requirement already up-to-date: numpy in c:\users\dbazoneny\anaconda3\lib\site-packages (1.21.2)


In [145]:
import numpy as np

### Question 1

What's the version of NumPy that you installed?

In [146]:
np.__version__

'1.21.2'

### Question 2

What's the version of Pandas?

In [147]:
import pandas as pd
pd.__version__

'1.3.2'

### Getting the data

For this homework, we'll use the same dataset as for the next session - the car price dataset.

In [148]:
df = pd.read_csv('cardataset.csv')

In [149]:
df.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

### Question 3

What's the average price of BMW cars in the dataset?

In [150]:
df[df['Make']=='BMW']['MSRP'].mean()

61546.76347305389

In [151]:
#df.groupby('Make')['MSRP'].agg('mean')

### Question 4

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [152]:
df_2015 = df[df['Year']>=2015]

In [153]:
df_2015['Engine HP'].isnull().sum()

51

In [154]:
df_2015.Year.unique()

array([2017, 2016, 2015], dtype=int64)

### Question 5

Calculate the average "Engine HP" in the dataset.

Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.

Now, calcualte the average of "Engine HP" again.

Has it changed?

Round both means before answering this questions. You can use the round function for that:

In [155]:
#find missing values in EngineHP
df['Engine HP'].isnull().sum()

69

In [156]:
mean_hp = df['Engine HP'].mean()

In [157]:
round(mean_hp)

249

In [158]:
df.fillna({'Engine HP':mean_hp}, inplace=True)

In [159]:
df['Engine HP'].isnull().sum()

0

In [160]:
round(df['Engine HP'].mean())

249

### Question 6

Select all the "Rolls-Royce" cars from the dataset.

Select only columns "Engine HP", "Engine Cylinders", "highway MPG".

Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Invert XTX.

What's the sum of all the elements of the result?

Hint: if the result is negative, re-read the task one more time

In [161]:
df.Make.unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [162]:
df_RR = df[df['Make']=='Rolls-Royce']

In [163]:
df_RR = df_RR[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [164]:
df_RR.head(3)

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21

In [165]:
df_RR.shape

(31, 3)

In [166]:

# dropping duplicate values
df_RR.drop_duplicates(keep='first',inplace=True)
 
# length after removing duplicates
len(df_RR)

7

In [167]:
df_RR

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [168]:
df_RR.shape

(7, 3)

In [169]:
X = df_RR.values

In [170]:
X.shape

(7, 3)

In [171]:
type(X)

numpy.ndarray

In [172]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [173]:
X_transpose = X.T


In [174]:
X.shape,X_transpose.shape

((7, 3), (3, 7))

In [175]:
XTX = np.matmul(X_transpose,X)

In [176]:
XTX.shape

(3, 3)

In [177]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [178]:
inv_XTX = np.linalg.inv(XTX)

In [179]:
np.sum(inv_XTX)

0.032212320677486125

### Questions 7

Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the value of the first element of w?.

In [180]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [181]:
result=  np.matmul(inv_XTX,X_transpose)

In [182]:
w = np.matmul(result,y)

In [183]:
w

array([ 0.19989598, 31.02612262, 31.65378877])